package org.collectiveone.modules.activity;

public enum ActivityType {
	INITIATIVE_CREATED,
	SUBINITIATIVE_CREATED,
	INITIATIVE_EDITED,
	TOKENS_MINTED,
	PR_ASSIGNATION_CREATED,
	D_ASSIGNATION_CREATED,
	INITIATIVE_TRANSFER,
	PR_ASSIGNATION_DONE,
	ASSIGNATION_REVERT_ORDERED,
	ASSIGNATION_REVERT_CANCELLED,
	ASSIGNATION_REVERTED,
	ASSIGNATION_DELETED,
	INITIATIVE_DELETED
}
