package org.collectiveone.modules.activity;

public enum ActivityType {
	INITIATIVE_CREATED,
	SUBINITIATIVE_CREATED,
	INITIATIVE_EDITED,
	TOKENS_MINTED,
	PR_ASSIGNATION_CREATED,
	D_ASSIGNATION_CREATED
}
