package org.collectiveone.modules.activity.enums;

public enum ActivityType {
	INITIATIVE_CREATED,
	INITIATIVE_DELETED,
	INITIATIVE_EDITED,
	SUBINITIATIVE_CREATED,
	
	TOKEN_CREATED,
	TOKENS_MINTED,
	TOKENS_BURNT,
	INITIATIVE_TRANSFER,
	
	PR_ASSIGNATION_CREATED,
	PR_ASSIGNATION_DONE,
	D_ASSIGNATION_CREATED,
	ASSIGNATION_REVERT_ORDERED,
	ASSIGNATION_REVERT_CANCELLED,
	ASSIGNATION_REVERTED,
	ASSIGNATION_DELETED,
	
	MODEL_SECTION_CREATED,
	MODEL_SECTION_EDITED,
	MODEL_SECTION_DELETED,
	MODEL_SECTION_ADDED,
	MODEL_SECTION_REMOVED,
	MODEL_SECTION_MOVED,
	
	MODEL_CARDWRAPPER_CREATED,
	MODEL_CARDWRAPPER_MADE_SHARED,
	MODEL_CARDWRAPPER_MADE_COMMON,
	MODEL_CARDWRAPPER_ADDED,
	MODEL_CARDWRAPPER_EDITED,
	MODEL_CARDWRAPPER_MOVED,
	MODEL_CARDWRAPPER_REMOVED,
	MODEL_CARDWRAPPER_DELETED,
	
	CONSENT_STATUS_OPENED,
	CONSENT_STATUS_CLOSED,
	CONSENT_STATUS_REOPENED,
	
	CONSENT_POSITION_STATED,
	CONSENT_POSITION_CHANGED,
	
	MESSAGE_POSTED
}
