package org.collectiveone.modules.activity.enums;

public enum ActivityType {
	
	
	TOKEN_CREATED,
	TOKENS_MINTED,
	MODEL_SECTION_TRANSFER,
	
	PR_ASSIGNATION_CREATED,
	PR_ASSIGNATION_DONE,
	D_ASSIGNATION_CREATED,
	ASSIGNATION_REVERT_ORDERED,
	ASSIGNATION_REVERT_CANCELLED,
	ASSIGNATION_REVERTED,
	ASSIGNATION_DELETED,
	
	MODEL_SECTION_CREATED,
	MODEL_SECTION_EDITED,
	MODEL_SECTION_DELETED,
	MODEL_SECTION_ADDED,
	MODEL_SECTION_REMOVED,
	MODEL_SECTION_MOVED,
	
	MODEL_CARDWRAPPER_CREATED,
	MODEL_CARDWRAPPER_MADE_SHARED,
	MODEL_CARDWRAPPER_MADE_COMMON,
	MODEL_CARDWRAPPER_ADDED,
	MODEL_CARDWRAPPER_EDITED,
	MODEL_CARDWRAPPER_MOVED,
	MODEL_CARDWRAPPER_REMOVED,
	MODEL_CARDWRAPPER_DELETED,
	
	MESSAGE_POSTED
}
